<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="AirlineServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/AirlineServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/AirlineServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://ws.airline/">
    <import location="http://localhost:8080/Airline/AirlineService?wsdl" namespace="http://ws.airline/"/>
    <plnk:partnerLinkType name="AirlineControllerLinkType">
        <plnk:role name="AirlineControllerRole" portType="ns:AirlineController"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="AirlineLinkType">
        <plnk:role name="AirlineControllerRole" portType="ns:AirlineController"/>
    </plnk:partnerLinkType>
</definitions>
